//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gigs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gigs()
        {
            this.Notifications = new HashSet<Notifications>();
            this.AspNetUsers1 = new HashSet<AspNetUsers>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Venue { get; set; }
        public string ArtistId { get; set; }
        public byte GenreId { get; set; }
        public bool IsCanceled { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Genres Genres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notifications> Notifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers1 { get; set; }
    }
}
