//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GigHub
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotifications
    {
        public string UserID { get; set; }
        public int NotificationId { get; set; }
        public bool IsRead { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Notifications Notifications { get; set; }
    }
}
